export const ANIMATIONS_MAP = {
  // ANGRY: "angry",
  HIP_HOP_DANCING: "HIP_HOP_DANCING",
  RUMBA_DANCING: "RUMBA_DANCING",
  JOYFUL_JUMP: "JOYFUL_JUMP",
  THRILLER_PART_3: "THRILLER_PART_3",
  CAPOEIRA: "CAPOEIRA",
  CATWALK_WALK_TURN_180_TIGHT: "CATWALK_WALK_TURN_180_TIGHT",
  OFFENSIVE_IDLE: "OFFENSIVE_IDLE",
  MARTELO_2: "MARTELO_2",
  CHAPA_GIRATORIA: "CHAPA_GIRATORIA",
  BROOKLYN_UPROCK: "BROOKLYN_UPROCK",
  FLOATING: "FLOATING",
  ROBOT_HIP_HOP_DANCE: "ROBOT_HIP_HOP_DANCE",
  SURPRISED: "SURPRISED",
  SAMBA_DANCING: "SAMBA_DANCING",
  SITTING: "SITTING",
  JUMPING: "JUMPING",
  HIP_HOP_DANCING_2: "HIP_HOP_DANCING_2",
  SPIN_IN_PLACE: "SPIN_IN_PLACE",
  FIST_FIGHT_A: "FIST_FIGHT_A",
  BREAKDANCE_UPROCK_VAR_2: "BREAKDANCE_UPROCK_VAR_2",
  SWING_DANCING: "SWING_DANCING",
  GOALKEEPER_DROP_KICK: "GOALKEEPER_DROP_KICK",
  BREAKDANCE_ENDING_2: "BREAKDANCE_ENDING_2",
  KICKING: "KICKING",
  HIP_HOP_DANCING_3: "HIP_HOP_DANCING_3",
  JAZZ_DANCING: "JAZZ_DANCING",
};

// Define the glTF assets that will represent the host's animations
export const ANIMATION_FILES = [
  "/models/animations/alien/stand_idle.glb",
  "/models/animations/alien/lipsync.glb",
  "/models/animations/alien/gesture.glb",
  "/models/animations/alien/emote.glb",
  "/models/animations/alien/face_idle.glb",
  "/models/animations/alien/blink.glb",
  "/models/animations/alien/poi.glb",
  // Custom animations
  // Need to be consumed in the same order as they are defined later
  "/models/animations/alien/hip_hop_dancing.glb",
  "/models/animations/alien/rumba_dancing.glb",
  "/models/animations/alien/joyful_jump.glb",
  "/models/animations/alien/thriller_part_3.glb",
  "/models/animations/alien/capoeira.glb",
  "/models/animations/alien/catwalk_walk_turn_180_tight.glb",
  "/models/animations/alien/offensive_idle.glb",
  "/models/animations/alien/martelo_2.glb",
  "/models/animations/alien/chapa_giratoria.glb",
  "/models/animations/alien/brooklyn_uprock.glb",
  "/models/animations/alien/floating.glb",
  "/models/animations/alien/robot_hip_hop_dance.glb",
  "/models/animations/alien/surprised.glb",
  "/models/animations/alien/samba_dancing.glb",
  "/models/animations/alien/sitting.glb",
  "/models/animations/alien/jumping.glb",
  "/models/animations/alien/hip_hop_dancing_2.glb",
  "/models/animations/alien/spin_in_place.glb",
  "/models/animations/alien/fist_fight_a.glb",
  "/models/animations/alien/breakdance_uprock_var_2.glb",
  "/models/animations/alien/swing_dancing.glb",
  "/models/animations/alien/goalkeeper_drop_kick.glb",
  "/models/animations/alien/breakdance_ending_2.glb",
  "/models/animations/alien/kicking.glb",
  "/models/animations/alien/hip_hop_dancing_3.glb",
  "/models/animations/alien/jazz_dancing.glb",
];

export const GRATITUDE_PHRASES = [
  "You're the best!",
  "Bless your heart!",
  "I really appreciate it!",
  "You're too kind!",
  "It really means a lot to me!",
  "I appreciate you so much!",
  "Big thank you!",
  "You're awesome!",
  "You've warmed my heart!",
  "I am beyond grateful!",
  "Feeling spoiled!",
  "God bless you!",
  "Thank you! Thank you! Thank you!",
  "Lots of love!",
  "Legend!",
  "You've made my day!",
  "You are amazing!",
  "I wish you and your family health and prosperity!",
  "You are a selfless human being!",
  "Thank you! You are so generous!",
  "Sending you my warmest wishes and blessings!",
  "Wishing you a relaxing and stress free day!",
  "Wishing you lots of love, joy and happiness!",
  "May the year ahead be full of contentment and joy!",
  "May your life be filled with moments of love, laughter and goodwill!",
  "Wishing you and your loved ones peace, health, happiness, and prosperity!",
  "Let the spirit of love gently fill your heart and home!",
];

export const DEFAULT_MANUAL_SPEECH = `Hi there! My name is Phendran! If you follow, share, and send gifts I will show you my appreciation!`;
